version: "3.3"
services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: flask-app:latest
        working_dir: /opt/app/
        command: bash run.sh
        ports:
            - 5000:5000
        volumes:
            - ./app/:/opt/app/
        environment:
            FLASK_APP: hello.py
        stdin_open: true
        tty: true
        expose:
            - 5000
